-- Seed discount coupons for 5%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%

INSERT INTO coupons (code, name, discount_type, discount_value, min_order_amount, max_discount_amount, usage_limit, used_count, status, created_at, updated_at) VALUES
  ('GIAM5', 'Giảm giá 5%', 'PERCENT', 5.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE5', 'Ưu đãi 5%', 'PERCENT', 5.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM10', 'Giảm giá 10%', 'PERCENT', 10.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE10', 'Ưu đãi 10%', 'PERCENT', 10.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM20', 'Giảm giá 20%', 'PERCENT', 20.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE20', 'Ưu đãi 20%', 'PERCENT', 20.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CHAO2026', 'Chào năm mới 2026 - Giảm 20%', 'PERCENT', 20.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM30', 'Giảm giá 30%', 'PERCENT', 30.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE30', 'Ưu đãi 30%', 'PERCENT', 30.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('LINGOFLOW', 'Tri ân LingoFlow - Giảm 30%', 'PERCENT', 30.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM40', 'Giảm giá 40%', 'PERCENT', 40.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE40', 'Ưu đãi 40%', 'PERCENT', 40.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM50', 'Giảm giá 50%', 'PERCENT', 50.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE50', 'Ưu đãi 50%', 'PERCENT', 50.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('HALF50', 'Nửa giá 50%', 'PERCENT', 50.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM60', 'Giảm giá 60%', 'PERCENT', 60.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE60', 'Ưu đãi 60%', 'PERCENT', 60.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM70', 'Giảm giá 70%', 'PERCENT', 70.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE70', 'Ưu đãi 70%', 'PERCENT', 70.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM80', 'Giảm giá 80%', 'PERCENT', 80.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE80', 'Ưu đãi 80%', 'PERCENT', 80.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('GIAM90', 'Giảm giá 90%', 'PERCENT', 90.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SALE90', 'Ưu đãi 90%', 'PERCENT', 90.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('SUPER90', 'Siêu khuyến mãi 90%', 'PERCENT', 90.00, 0.00, NULL, NULL, 0, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
