CREATE TABLE IF NOT EXISTS ai_message_feedbacks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  message_id BIGINT  NULL,
  user_id BIGINT  NOT NULL,
  rating VARCHAR(20) NOT NULL,
  comment TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  CONSTRAINT fk_ai_feedbacks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
