-- V2__data.sql already seeds the initial roles, users, courses, chapters, and
-- lessons. This version is kept as a no-op so fresh Flyway runs preserve the
-- migration order without inserting duplicate primary keys.
--
-- Lesson content enrichment is handled by V7__enrich_lesson_content.sql.
