-- V1__create_schema.sql already creates the vocabulary_progress learning-state
-- columns expected by the JPA entity. This version is kept as a no-op so fresh
-- Flyway runs preserve migration order without adding duplicate columns.
